### ISSUE TITLE
Does this library compile?

### ISSUE THREAD

**Issue by maxsvetlik** [ut-amrl/robofleet_client_lib#5]
In `encode.hpp` and `decode.hpp`  there are references to the generated schema, e.g. 
```
template <>
struct flatbuffers_type_for<RobotStatus> {
  typedef fb::amrl_msgs::RobofleetStatus type;
};
```
When including this library in a C++ project, the `fb` namespace is not picked up here. As far as I can tell this is accurate because there's no included reference to `fb::amrl_msgs::*` since`schema_generated.h` isn't included. 
Is my understanding correct? Is this project working as-is for others?

**Comment by kvsikand** [comment]
This library is being actively used in both `robofleet_client` and `robofleet_base_client`. do you have the example project in which you are trying to use this library?

**Comment by maxsvetlik** [comment]
Not one that's public / easy to view, though all it does is include the `encode.hpp`, `decode.hpp`, and `schema_generated.h` files. 
It seems that if I include `schema_generated.h` _before_ `encode.hpp` and `decode.hpp` the project compiles without a problem. I suppose this makes sense, though I can't convince myself that it's how it _should_ be.

Why wouldn't `encode` and `decode` not include `schema_generate.h` since they both reference it?
